name: ta_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^10.0.0-beta.4
  get_it: ^8.0.3
  go_router: ^14.7.2
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  hydrated_bloc: ^10.0.0
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.5.0
  path_provider: ^2.1.2
  retrofit: ^4.1.0
  sentry_flutter: ^8.13.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.7
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.dev
