name: ta_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  http: ^1.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  flutter_toggle_tab: ^1.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/devicon_google.svg
    - assets/icons/fluent_vehicle-car-profile-ltr-clock-16-filled.svg
    - assets/icons/material-symbols_credit-card.svg
    - assets/icons/material-symbols_credit-card-blk.svg
    - assets/icons/material-symbols_money-bag-rounded.svg
    - assets/icons/material-symbols_savings-rounded.svg
    - assets/icons/material-symbols_smart-toy-rounded.svg
    - assets/icons/material-symbols_wallet.svg
    - assets/icons/mdi_car-sports-utility-vehicle.svg
    - assets/icons/mdi_dots-horizontal.svg
    - assets/icons/mdi_people.svg
    - assets/icons/mdi_property-tag.svg
