name: ta_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0-0 <4.0.0"

dependencies:
  another_xlider: ^3.0.2
  bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  easy_latex: ^1.0.2
  equatable: ^2.0.7
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0
  flutter_inset_shadow: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.2
  jwt_decode: ^0.3.1
  month_picker_dialog: ^6.0.2
  provider: ^6.1.2
  quickalert: ^1.1.0
  toggle_switch: ^2.3.0
  two_dimensional_scrollables: ^0.3.3
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.dev
    - assets/icons/devicon_google.svg
    - assets/icons/fluent_vehicle-car-profile-ltr-clock-16-filled.svg
    - assets/icons/material-symbols_credit-card.svg
    - assets/icons/material-symbols_credit-card-blk.svg
    - assets/icons/material-symbols_money-bag-rounded.svg
    - assets/icons/material-symbols_savings-rounded.svg
    - assets/icons/material-symbols_smart-toy-rounded.svg
    - assets/icons/material-symbols_wallet.svg
    - assets/icons/mdi_car-sports-utility-vehicle.svg
    - assets/icons/mdi_dots-horizontal.svg
    - assets/icons/mdi_people.svg
    - assets/icons/mdi_property-tag.svg
    - assets/img/10078322.png
    - assets/img/budgeting_background.png
