// lib/core/constants/category_mapping.dart
const Map<String, List<String>> categoryMapping = {
  'Kas': ['Uang Tunai', 'Uang Rekening Bank', 'Uang E-Wallet'],
  'Piutang': ['Piutang'],
  'Bangunan': ['Rumah', 'Apartemen', 'Ruko', 'Gudang', 'Kios'],
  'Tanah': ['Properti Sewa'],
  'Peralatan': ['Kendaraan', 'Elektronik', 'Furnitur'],
  'Surat Berharga': ['Saham', 'Obligasi', 'Reksadana'],
  'Investasi Alternatif': ['Kripto'],
  'Aset Pribadi': ['Koleksi', 'Perhiasan'],
  'Hutang': ['Saldo Kartu Kredit', 'Tagihan', 'Cicilan', 'Pajak'],
  'Hutang Perjanjian Tertulis': ['Pinjaman'],
  'Pinjaman Jangka Panjang': ['Pinjaman Properti'],
  'Pendapatan dari Pekerjaan': ['Gaji', 'Upah', 'Bonus', 'Commission'],
  'Pendapatan dari Investasi': ['Dividen'],
  'Pendapatan Bunga': ['Bunga'],
  'Keuntungan dari Aset': ['Untung Modal'],
  'Pendapatan Jasa': ['Freelance'],
  'Tabungan': ['Tabungan'],
  'Makanan & Minuman': ['Makanan', 'Minuman'],
  'Hadiah & Donasi': ['Hadiah', 'Donasi'],
  'Transportasi': ['Kendaraan Pribadi', 'Transportasi Umum', 'Bahan bakar'],
  'Kesehatan & Medis': ['Kesehatan', 'Medis'],
  'Perawatan Pribadi & Pakaian': ['Perawatan Pribadi', 'Pakaian'],
  'Hiburan & Rekreasi': ['Hiburan', 'Rekreasi'],
  'Pendidikan & Pembelajaran': ['Pendidikan', 'Pembelajaran'],
  'Kewajiban Finansial (pinjaman, pajak, asuransi)': [
    'Bayar pinjaman',
    'Bayar pajak',
    'Bayar asuransi',
  ],
  'Perumahan dan Kebutuhan Sehari-hari': ['Perumahan', 'Kebutuhan Sehari-hari'],
  'Ekuitas': ['Ekuitas'],
};
